extraction:
  cpp:
    prepare:
      packages:
        - liblzo2-dev
        - libcrypto++-dev
        - libkyotocabinet-dev
        - libyaml-cpp-dev
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DBUILD_GTEST=OFF -DINSTALL_GTEST=OFF ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
